apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  clusterIP: None
  selector:
    app: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment
      - name: payment-sidecar
        image: hazelcast/turbine-sidecar
        env:
          - name: CLUSTER_ADDRESS
            value: "hz-hazelcast:5701"
          - name: APP_PORT
            value: "3002"
          - name: "TURBINE_POD_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
